### ISSUE TITLE
This application cannot tree shake icons fonts

### ISSUE THREAD

**Issue by ameenvga** [Ahmadre/FlutterIconPicker#45] opened 2022-04-21 11:33 UTC
When I run the following command
`flutter build apk --split-per-abi`

I get this error and fail the apk building process

`This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - file:///C:/Users/ameen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_iconpicker-3.1.3/lib/Serialization/iconDataSerialization.dart:76:16

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1`

**Comment by ameenvga** [comment] 2022-04-21 11:34
Used latest version 3.1.3

**Comment by ameenvga** [comment] 2022-04-22 04:29
@Ahmadre

**Comment by Ahmadre** [comment] 2022-04-26 21:31
Duplicate of: https://github.com/Ahmadre/FlutterIconPicker/issues/40#issuecomment-1040309050

Please search for related issues. There's a lot explained why you need to add this flag because by flutter.

**Closed by Ahmadre** 2022-04-26 21:31 UTC
