### ISSUE TITLE
I'm having a failure when trying to build APK

### ISSUE THREAD

**Issue by BermyToiga** [Ahmadre/FlutterIconPicker#20] opened 2020-12-07 16:01 UTC
Hi, I'm getting this error when I run "flutter build apk":

This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - file:///Users/zara/devel/tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_iconpicker-2.2.2/lib/Serialization/iconDataSerialization.dart:22:14

It points to line 22 of iconDataSerialization.dart.

I'm a fairly novice app developer so no idea what to do about this. Any suggestions would be great

**Comment by Ahmadre** [comment] 2020-12-15 13:11
Duplicate of: https://github.com/Ahmadre/FlutterIconPicker/issues/9

**Closed by Ahmadre** 2020-12-15 13:11 UTC
