### ISSUE TITLE
whatsapp icon problem

### ISSUE THREAD

**Issue by ahmetbalkan** [Ahmadre/FlutterIconPicker#56] opened 2023-02-18 09:41 UTC
![image](https://user-images.githubusercontent.com/48199986/219853433-25603504-b5b5-4a2d-a45d-69a0ea72ce66.png)

**Comment by nicolaspernoud** [comment] 2023-02-20 08:27
Duplicate of #53

**Comment by Ahmadre** [comment] 2023-06-04 18:04
A new version is published.

See: https://github.com/Ahmadre/FlutterIconPicker/issues/53#issuecomment-1575658783

**Closed by Ahmadre** 2023-06-04 18:04 UTC
